version: "3"

services:
  mageia:
    image: armmageia
    container_name: armmageia
    restart: always
    build: /root
    # needed as iurt uses mount/umount and ns
    privileged: true
    ports:
      - "2222:2222"
    volumes:
      - /root/.ssh:/root/.ssh
