#!/bin/bash
#
# Creating Mageia docker images and containers on Debian based ARM system
#
# Internal port value for unpriviledge launch of sshd
IPORT=2222
# Externally accessible via this port with appropriate SSH keys - may differ
EPORT=2222

cat > entrypoint.sh << EOF
/usr/sbin/sshd -D -p $IPORT &
sleep infinity
EOF
chmod 755 entrypoint.sh

CTNNAME=armmageia
cat > docker-compose.yml << EOF
version: "3"

services:
  mageia:
    image: armmageia
    container_name: $CTNNAME
    restart: always
    build: /root
    # needed as iurt uses mount/umount and ns
    privileged: true
    ports:
      - "$EPORT:$IPORT"
    volumes:
      - /root/.ssh:/root/.ssh
EOF
chmod 644 docker-compose.yml

for i in mga-arm-1 mga-arm-2; do
	echo "Working on system $i"
	echo "--------------------"
	ssh $i apt update -y
	ssh $i apt install -y apparmor docker.io docker-compose
	scp -p docker-compose.yml Dockerfile iurt entrypoint.sh mageia-build-image ${i}:
	ssh $i ./mageia-build-image $CTNNAME
	# check it works
	echo -n "Distribution installed: "
	ssh -p $EPORT iurt@$i lsb_release -a
	echo -n "Number of packages installed: "
	ssh -p $EPORT iurt@$i rpm -aq | wc -l
done

rm -f docker-compose.yml entrypoint.sh
