#!/usr/bin/bash

ARCH=aarch64
NODE=iurt@mga-arm-1
EPORT=2222
MIRROR=http://fr2.rpmfind.net/linux/mageia/distrib
#PKG=project-builder-0.16.1-2.mga9.src.rpm
PKG=bc-1.07.1-7.mga9.src.rpm
SPOOL=/home/iurt/tmp/mageia-iurt
MGAV=9

ssh -p $EPORT ${NODE} curl -O $MIRROR/$MGAV/SRPMS/core/release/${PKG}
ssh -p $EPORT $NODE iurt --copy_srpm --group  --config local_spool $SPOOL --no_rsync --repository $MIRROR --chrooted-urpmi $MIRROR -p foo@foo.net --rebuild $MGAV $ARCH $PKG
ssh -p $EPORT $NODE ls -alR $SPOOL/*.rpm
scp -p -P $EPORT ${NODE}:$SPOOL/*.rpm .
